// Generated by scripts/generate-design-tokens.mjs from config/design-tokens.json.
// Do not edit by hand.

import SwiftUI

enum MaterialTheme {
    static let background = Color(red: 0.925, green: 0.941, blue: 0.965)
    static let surface = Color(red: 1, green: 1, blue: 1, opacity: 0.7)
    static let surfaceStrong = Color(red: 1, green: 1, blue: 1, opacity: 0.92)
    static let surfaceTint = Color(red: 0.965, green: 0.976, blue: 0.992, opacity: 0.72)
    static let surfaceFloating = Color(red: 1, green: 1, blue: 1, opacity: 0.86)
    static let surfaceChrome = Color(red: 0.973, green: 0.984, blue: 1, opacity: 0.64)
    static let primary = Color(red: 0.039, green: 0.518, blue: 1)
    static let primaryDark = Color(red: 0.027, green: 0.247, blue: 0.471)
    static let accentDanger = Color(red: 0.753, green: 0.149, blue: 0.176)
    static let accentDangerSoft = Color(red: 1, green: 0.969, blue: 0.969)
    static let accentSuccess = Color(red: 0.059, green: 0.522, blue: 0.247)
    static let accentSuccessSoft = Color(red: 0.918, green: 0.969, blue: 0.937)
    static let accentWarning = Color(red: 0.78, green: 0.471, blue: 0.059)
    static let accentWarningSoft = Color(red: 1, green: 0.965, blue: 0.847)
    static let ink = Color(red: 0.075, green: 0.082, blue: 0.094)
    static let muted = Color(red: 0.365, green: 0.388, blue: 0.431)
    static let mutedOverlay = Color(red: 0.235, green: 0.235, blue: 0.263, opacity: 0.72)
    static let hairline = Color(red: 1, green: 1, blue: 1, opacity: 0.58)
    static let separator = Color(red: 0, green: 0, blue: 0, opacity: 0.075)
    static let shadow = Color(red: 0, green: 0, blue: 0, opacity: 0.16)
    static let glow = Color(red: 0, green: 0.478, blue: 0.78, opacity: 0.13)
    static let canvasGridX = Color(red: 0.039, green: 0.518, blue: 1, opacity: 0.035)
    static let canvasGridY = Color(red: 0.039, green: 0.518, blue: 1, opacity: 0.03)
    static let canvasChromeStart = Color(red: 1, green: 1, blue: 1, opacity: 0.76)
    static let canvasChromeEnd = Color(red: 0.902, green: 0.933, blue: 0.973, opacity: 0.86)
    static let radiusSmall: CGFloat = 8
    static let radiusMedium: CGFloat = 12
    static let radiusPanel: CGFloat = 16
    static let radiusStage: CGFloat = 14
    static let panelPadding: CGFloat = 14
    static let viewportPadding: CGFloat = 34
    static let canvasGridSize: CGFloat = 24
}
